# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'produto_atualizapreco.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import psycopg2
import variaveisControle

host = variaveisControle.host
user = variaveisControle.user
password = variaveisControle.password
database = variaveisControle.database
port = variaveisControle.port

class Ui_AtualizarProduto(object):
    def setupUi(self, AtualizarProduto):
        AtualizarProduto.setObjectName("AtualizarProduto")
        AtualizarProduto.resize(457, 215)
        self.centralwidget = QtWidgets.QWidget(AtualizarProduto)
        self.centralwidget.setObjectName("centralwidget")
        self.cancelar_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancelar_button.setGeometry(QtCore.QRect(130, 130, 101, 71))
        self.cancelar_button.setStyleSheet("image: url(:cliente/logo_cliente/cliente.png)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo_excluir/excluir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelar_button.setIcon(icon)
        self.cancelar_button.setObjectName("cancelar_button")
        self.valor_produto = QtWidgets.QLabel(self.centralwidget)
        self.valor_produto.setGeometry(QtCore.QRect(100, 70, 91, 20))
        self.valor_produto.setObjectName("valor_produto")
        self.search_valor = QtWidgets.QLineEdit(self.centralwidget)
        self.search_valor.setGeometry(QtCore.QRect(170, 70, 151, 20))
        self.search_valor.setObjectName("search_valor")
        self.atualizar_button = QtWidgets.QPushButton(self.centralwidget)
        self.atualizar_button.setGeometry(QtCore.QRect(250, 130, 101, 71))
        self.atualizar_button.setStyleSheet("image: url(:cliente/logo_cliente/cliente.png)")
        self.atualizar_button.setObjectName("atualizar_button")
        self.search_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.search_nome.setGeometry(QtCore.QRect(170, 40, 151, 20))
        self.search_nome.setObjectName("search_nome")
        self.nome_produto = QtWidgets.QLabel(self.centralwidget)
        self.nome_produto.setGeometry(QtCore.QRect(80, 40, 91, 20))
        self.nome_produto.setObjectName("nome_produto")
        AtualizarProduto.setCentralWidget(self.centralwidget)

        self.retranslateUi(AtualizarProduto)
        QtCore.QMetaObject.connectSlotsByName(AtualizarProduto)

    def retranslateUi(self, AtualizarProduto):
        _translate = QtCore.QCoreApplication.translate
        AtualizarProduto.setWindowTitle(_translate("AtualizarProduto", "MainWindow"))
        self.cancelar_button.setText(_translate("AtualizarProduto", "Cancelar"))
        self.valor_produto.setText(_translate("AtualizarProduto", "Novo valor:"))
        self.atualizar_button.setText(_translate("AtualizarProduto", "Atualizar valor"))
        self.nome_produto.setText(_translate("AtualizarProduto", "Nome do Produto:"))

        #botoes
        self.cancelar_button.clicked.connect(lambda: self.sairTela(AtualizarProduto))
        self.atualizar_button.clicked.connect(self.Atualizar)
        
        #Atualiza preço
    def Atualizar(self):
        nomeProduto = self.search_nome.text()
        valorProduto = self.search_valor.text()
        connection = psycopg2.connect(user=user,
                                password=password,
                                host=host,
                                port=port,
                                database=database)
        mycursor = connection.cursor()
        consultaSql = "SELECT ATUALIZA('"+ nomeProduto + "'," + valorProduto + ");"
        print(consultaSql)
        try:
            mycursor.execute(consultaSql)
            connection.commit()
        except:
            print ("erro")
        self.search_nome.setText("")
        self.search_valor.setText("")
        mycursor.close()  

        #Fecha a tela
    def sairTela(self, AtualizarProduto):
        AtualizarProduto.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AtualizarProduto = QtWidgets.QMainWindow()
    ui = Ui_AtualizarProduto()
    ui.setupUi(AtualizarProduto)
    AtualizarProduto.show()
    sys.exit(app.exec_())
