# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'funcionario.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_funcionarioPage(object):
    def setupUi(self, funcionarioPage):
        funcionarioPage.setObjectName("funcionarioPage")
        funcionarioPage.resize(830, 425)
        self.cadastroCli_button = QtWidgets.QPushButton(funcionarioPage)
        self.cadastroCli_button.setGeometry(QtCore.QRect(300, 10, 101, 71))
        self.cadastroCli_button.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo_cadastro/cadastrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cadastroCli_button.setIcon(icon)
        self.cadastroCli_button.setObjectName("cadastroCli_button")
        self.excluirCli_button = QtWidgets.QPushButton(funcionarioPage)
        self.excluirCli_button.setGeometry(QtCore.QRect(400, 10, 101, 71))
        self.excluirCli_button.setStyleSheet("image: url(:cliente/logo_cliente/cliente.png)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo_excluir/excluir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.excluirCli_button.setIcon(icon1)
        self.excluirCli_button.setObjectName("excluirCli_button")
        self.retorno_bd = QtWidgets.QTableWidget(funcionarioPage)
        self.retorno_bd.setGeometry(QtCore.QRect(10, 120, 811, 291))
        self.retorno_bd.setObjectName("retorno_bd")
        self.retorno_bd.setColumnCount(8)
        self.retorno_bd.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.retorno_bd.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.retorno_bd.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.retorno_bd.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.retorno_bd.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.retorno_bd.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.retorno_bd.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.retorno_bd.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.retorno_bd.setHorizontalHeaderItem(7, item)
        self.CPFClient_3 = QtWidgets.QLabel(funcionarioPage)
        self.CPFClient_3.setGeometry(QtCore.QRect(260, 90, 91, 20))
        self.CPFClient_3.setObjectName("CPFClient_3")
        self.search_cpf_3 = QtWidgets.QLineEdit(funcionarioPage)
        self.search_cpf_3.setGeometry(QtCore.QRect(350, 90, 181, 20))
        self.search_cpf_3.setText("")
        self.search_cpf_3.setObjectName("search_cpf_3")

        self.retranslateUi(funcionarioPage)
        QtCore.QMetaObject.connectSlotsByName(funcionarioPage)

    def retranslateUi(self, funcionarioPage):
        _translate = QtCore.QCoreApplication.translate
        funcionarioPage.setWindowTitle(_translate("funcionarioPage", "Form"))
        self.cadastroCli_button.setText(_translate("funcionarioPage", "Cadastro"))
        self.excluirCli_button.setText(_translate("funcionarioPage", "Excluir"))
        item = self.retorno_bd.horizontalHeaderItem(0)
        item.setText(_translate("funcionarioPage", "ID"))
        item = self.retorno_bd.horizontalHeaderItem(1)
        item.setText(_translate("funcionarioPage", "Nome"))
        item = self.retorno_bd.horizontalHeaderItem(2)
        item.setText(_translate("funcionarioPage", "Telefone"))
        item = self.retorno_bd.horizontalHeaderItem(3)
        item.setText(_translate("funcionarioPage", "Email"))
        item = self.retorno_bd.horizontalHeaderItem(4)
        item.setText(_translate("funcionarioPage", "CPF"))
        item = self.retorno_bd.horizontalHeaderItem(5)
        item.setText(_translate("funcionarioPage", "Cargo"))
        item = self.retorno_bd.horizontalHeaderItem(6)
        item.setText(_translate("funcionarioPage", "Salário"))
        item = self.retorno_bd.horizontalHeaderItem(7)
        item.setText(_translate("funcionarioPage", "Carteira de Trabalho"))
        self.CPFClient_3.setText(_translate("funcionarioPage", "Procurar por CPF:"))
import logo_adicionarCesta_rc
import logo_cadastro_rc
import logo_cestaCli_rc
import logo_excluir_rc
import logo_excluircesta_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    funcionarioPage = QtWidgets.QWidget()
    ui = Ui_funcionarioPage()
    ui.setupUi(funcionarioPage)
    funcionarioPage.show()
    sys.exit(app.exec_())
